# Generated by Django 4.1.6 on 2023-02-07 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mydrone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], max_length=20)),
                ('weight_limit', models.IntegerField(validators=[mydrone.models.max_weight])),
                ('battery_capacity', models.IntegerField()),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w-]+$')])),
                ('weight', models.IntegerField()),
                ('code', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$')])),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydrone.drone')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydrone.medication')),
            ],
        ),
        migrations.CreateModel(
            name='EnventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateTimeField(auto_now_add=True)),
                ('battery', models.IntegerField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mydrone.drone')),
            ],
        ),
    ]
